version: '3.8'

services:
  mcp-servers:
    build:
      context: .
      dockerfile: config/docker/Dockerfile.dev
    container_name: sme-boost-mcp-servers-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - redis
    networks:
      - mcp-network
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: sme-boost-redis-dev
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - mcp-network
    restart: unless-stopped

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: sme-boost-redis-ui-dev
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  mcp-network:
    driver: bridge
